# Site settings
baseurl = "https://ahmedash.com/"
languageCode = "en-us"
title = "Ahmed Ashraf"
theme = "hugo-tailwind-journal"
PygmentsStyle = "github"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-93950970-1"
# Publisher Directory
publishDir = "public"

[params]
	name = "Ahmed Ashraf"
	description = "Backend Engineer @GetYourGuide"
	bio = "Backend Engineer"
	# Enter optionally your twitter account
	twitter = "ahmedash95"
	enableRSS = false

	author = "Ahmed Ashraf"
    avatar = "images/avatar.png"

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.
	twitterCardImage = "avatar"

	showLatestPosts = true
	enableShare = true
	enableGoogleAnalytics = true
	enableDisqus = true
	disqusShortname = "ahmedash-com"

	# Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = "© Copyright 2019 Ahmed Ashraf"
	# Sharing options and author information in posts
	aboutAuthor = ""
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "rounded"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/ahmedash95"
    facebook = "https://www.facebook.com/ahmedash95"
    github   = "https://www.github.com/ahmedash95"
    #dribble  = ""
